/**
 * Curated Google Business Profile category list for the citation
 * onboarding form. Restricting input to known GBP categories prevents
 * BrightLocal submission failures from typos / non-canonical names.
 *
 * Sourced from Google's public GBP category taxonomy. Weighted toward
 * home services (Local Lead Machine's primary vertical) plus common
 * food, retail, and professional-services categories. If a client needs
 * a category not in this list, add it here rather than free-typing.
 */

export const GBP_CATEGORIES: readonly string[] = [
  // Home services — plumbing
  'Plumber',
  'Drainage service',
  'Septic system service',
  'Water filter supplier',
  'Water softening equipment supplier',
  'Hot water system supplier',
  'Sewage disposal service',
  'Boiler supplier',

  // Home services — HVAC
  'HVAC contractor',
  'Air conditioning contractor',
  'Air conditioning repair service',
  'Heating contractor',
  'Furnace repair service',
  'Heating equipment supplier',
  'Air duct cleaning service',
  'Refrigerator repair service',

  // Home services — electrical
  'Electrician',
  'Electrical installation service',
  'Electrical repair shop',
  'Lighting contractor',
  'Solar energy contractor',
  'Solar energy equipment supplier',
  'Generator shop',

  // Home services — roofing & exterior
  'Roofing contractor',
  'Roofing supply store',
  'Gutter cleaning service',
  'Siding contractor',
  'Window installation service',
  'Window cleaning service',
  'Insulation contractor',
  'Chimney sweep',
  'Chimney services',

  // Home services — general contracting & remodeling
  'General contractor',
  'Construction company',
  'Home builder',
  'Remodeler',
  'Bathroom remodeler',
  'Kitchen remodeler',
  'Basement waterproofing service',
  'Foundation',
  'Concrete contractor',
  'Masonry contractor',
  'Drywall contractor',
  'Flooring contractor',
  'Tile contractor',
  'Carpet installer',
  'Hardwood floor refinishing service',
  'Painter',
  'Painting',
  'Wallpaper installer',
  'Door supplier',
  'Garage door supplier',
  'Cabinet maker',
  'Cabinet store',
  'Countertop store',
  'Carpenter',
  'Handyman',
  'Deck builder',
  'Fence contractor',
  'Pool cleaning service',
  'Swimming pool contractor',
  'Hot tub repair service',

  // Home services — landscaping & outdoor
  'Landscaper',
  'Landscape designer',
  'Lawn care service',
  'Lawn mower repair service',
  'Lawn sprinkler system contractor',
  'Tree service',
  'Arborist service',
  'Snow removal service',
  'Excavating contractor',
  'Paving contractor',
  'Patio enclosure supplier',

  // Home services — cleaning & pest
  'House cleaning service',
  'Cleaning service',
  'Commercial cleaning service',
  'Carpet cleaning service',
  'Pressure washing service',
  'Pest control service',
  'Exterminator',
  'Wildlife and animal removal service',
  'Mold testing service',
  'Water damage restoration service',
  'Fire damage restoration service',

  // Home services — security & misc
  'Security system installer',
  'Security system supplier',
  'Locksmith',
  'Moving company',
  'Self-storage facility',
  'Junk removal service',
  'Garbage collection service',
  'Appliance repair service',
  'Small appliance repair service',
  'Garage door installer',

  // Automotive
  'Auto repair shop',
  'Auto body shop',
  'Auto glass shop',
  'Auto tune up service',
  'Brake shop',
  'Car dealer',
  'Used car dealer',
  'Car detailing service',
  'Car wash',
  'Mechanic',
  'Oil change service',
  'Tire shop',
  'Towing service',
  'Transmission shop',
  'Truck repair shop',
  'Motorcycle repair shop',

  // Food & beverage
  'Restaurant',
  'Cafe',
  'Coffee shop',
  'Bakery',
  'Doughnut shop',
  'Bagel shop',
  'Sandwich shop',
  'Pizza restaurant',
  'Fast food restaurant',
  'Hamburger restaurant',
  'Mexican restaurant',
  'Italian restaurant',
  'Chinese restaurant',
  'Japanese restaurant',
  'Sushi restaurant',
  'Thai restaurant',
  'Indian restaurant',
  'Vietnamese restaurant',
  'Korean restaurant',
  'Mediterranean restaurant',
  'Steakhouse',
  'Seafood restaurant',
  'Vegetarian restaurant',
  'Vegan restaurant',
  'Breakfast restaurant',
  'Brunch restaurant',
  'Buffet restaurant',
  'Family restaurant',
  'Fine dining restaurant',
  'Bar',
  'Bar & grill',
  'Pub',
  'Sports bar',
  'Wine bar',
  'Brewery',
  'Cocktail bar',
  'Ice cream shop',
  'Juice shop',
  'Smoothie shop',
  'Tea house',
  'Catering service',
  'Food truck',
  'Deli',
  'Grocery store',
  'Butcher shop',
  'Wine store',
  'Liquor store',

  // Retail & shopping
  'Clothing store',
  "Women's clothing store",
  "Men's clothing store",
  "Children's clothing store",
  'Shoe store',
  'Jewelry store',
  'Watch store',
  'Eyewear store',
  'Sunglasses store',
  'Bookstore',
  'Toy store',
  'Hobby store',
  'Sporting goods store',
  'Bicycle store',
  'Outdoor sports store',
  'Pet store',
  'Pet supply store',
  'Furniture store',
  'Home goods store',
  'Hardware store',
  'Garden center',
  'Florist',
  'Gift shop',
  'Antique store',
  'Thrift store',
  'Pawn shop',
  'Convenience store',
  'Department store',
  'Shopping mall',
  'Mattress store',
  'Appliance store',
  'Electronics store',
  'Computer store',
  'Cell phone store',
  'Cosmetics store',
  'Beauty supply store',
  'Health food store',
  'Vitamin & supplements store',

  // Health & medical
  'Doctor',
  'Family practice physician',
  'Internist',
  'Pediatrician',
  'Dentist',
  'Dental clinic',
  'Orthodontist',
  'Cosmetic dentist',
  'Endodontist',
  'Periodontist',
  'Oral surgeon',
  'Pediatric dentist',
  'Optometrist',
  'Ophthalmologist',
  'Chiropractor',
  'Physical therapist',
  'Physical therapy clinic',
  'Massage therapist',
  'Acupuncture clinic',
  'Dermatologist',
  'Plastic surgeon',
  'Cosmetic surgeon',
  'Psychiatrist',
  'Psychologist',
  'Counselor',
  'Mental health service',
  'Mental health clinic',
  'Marriage or relationship counselor',
  'Addiction treatment center',
  'Rehabilitation center',
  'Pharmacy',
  'Medical clinic',
  'Urgent care center',
  'Walk-in clinic',
  'Hospital',
  'Veterinary care',
  'Animal hospital',
  'Audiologist',
  'Hearing aid store',
  'Podiatrist',
  'Naturopathic practitioner',

  // Beauty & wellness
  'Hair salon',
  'Barber shop',
  'Beauty salon',
  'Nail salon',
  'Eyebrow bar',
  'Eyelash salon',
  'Tanning salon',
  'Tattoo shop',
  'Piercing shop',
  'Spa',
  'Day spa',
  'Medical spa',
  'Skin care clinic',
  'Waxing hair removal service',
  'Laser hair removal service',
  'Permanent make-up clinic',
  'Hair removal service',
  'Yoga studio',
  'Pilates studio',
  'Gym',
  'Fitness center',
  'Personal trainer',
  'Boxing gym',
  'Martial arts school',
  'CrossFit gym',
  'Dance school',

  // Professional services
  'Lawyer',
  'Attorney',
  'Family law attorney',
  'Personal injury attorney',
  'Criminal justice attorney',
  'Divorce lawyer',
  'Estate planning attorney',
  'Immigration attorney',
  'Real estate attorney',
  'Tax attorney',
  'Bankruptcy attorney',
  'Business management consultant',
  'Marketing consultant',
  'Marketing agency',
  'Advertising agency',
  'Internet marketing service',
  'Web designer',
  'Software company',
  'Accountant',
  'Accounting firm',
  'Bookkeeping service',
  'Tax preparation service',
  'Tax consultant',
  'Financial planner',
  'Financial consultant',
  'Insurance agency',
  'Insurance broker',
  'Mortgage broker',
  'Mortgage lender',
  'Real estate agency',
  'Real estate agent',
  'Property management company',
  'Notary public',
  'Translator',
  'Architect',
  'Interior designer',
  'Engineering consultant',
  'Surveyor',
  'Graphic designer',
  'Photographer',
  'Wedding photographer',
  'Videographer',

  // Education & childcare
  'School',
  'Preschool',
  'Day care center',
  'Tutoring service',
  'Music school',
  'Driving school',
  'Language school',
  'Art school',

  // Pet services
  'Pet groomer',
  'Pet sitter',
  'Dog day care center',
  'Dog trainer',
  'Pet boarding service',

  // Events & entertainment
  'Event planner',
  'Wedding planner',
  'Banquet hall',
  'Wedding venue',
  'Party equipment rental service',
  'DJ service',
  'Live music venue',
  'Karaoke bar',
  'Bowling alley',
  'Movie theater',
  'Escape room center',

  // Travel & lodging
  'Hotel',
  'Motel',
  'Bed & breakfast',
  'Resort hotel',
  'Travel agency',
  'Tour operator',

  // Other common
  'Funeral home',
  'Cemetery',
  'Church',
  'Place of worship',
  'Non-profit organization',
  'Community center',
  'Recycling center',
  'Storage facility',
  'Print shop',
  'Sign shop',
  'Shipping and mailing service',
  'Post office',
  'Bank',
  'Credit union',
  'ATM',
];
