/**
 * Meta (Facebook) Conversions API client.
 *
 * Server-side companion to the client-side Pixel in
 * components/marketing/scan/MetaPixel.tsx. The Pixel alone misses
 * 30–50% of conversions on cold Meta traffic (iOS 14+ ATT opt-outs,
 * ad blockers, browser tracking-prevention). CAPI bypasses the
 * browser, sending the event server-to-server.
 *
 * Dedup mechanic:
 *   Pixel and CAPI fire the same logical event from two surfaces,
 *   tagged with the same event_id. Facebook dedupes by event_name +
 *   event_id (within a ~48-hour window). Caller must pass a UUID
 *   they ALSO pass to the client-side fbq call.
 *
 * Per Facebook spec, all PII (email, phone, names, DOB) must be
 * SHA-256 hashed before transport. Cookie identifiers (_fbp, _fbc),
 * the client IP, and the user-agent are sent in clear text — those
 * are technical identifiers, not PII.
 *
 * Env vars (server-side only):
 *   NEXT_PUBLIC_META_PIXEL_ID   — same id used by the client pixel
 *   META_CAPI_ACCESS_TOKEN      — generated in Facebook Events
 *                                  Manager → Settings → Conversions
 *                                  API → "Generate access token".
 *   META_CAPI_TEST_EVENT_CODE   — optional. When set, every CAPI
 *                                  event is tagged with this code so
 *                                  it appears in Events Manager →
 *                                  Test Events without polluting
 *                                  production attribution data.
 *
 * The function ALWAYS returns a Result object; it never throws.
 * Caller is expected to log non-`ok` results but not block the user
 * flow on a CAPI failure.
 */

import { createHash } from 'crypto';

const FB_API_VERSION = 'v18.0';

function sha256(value: string): string {
  return createHash('sha256').update(value).digest('hex');
}

/** Facebook PII normalization rules — lowercase + trim for email,
 *  strip non-digits for phone. Applied before hashing. */
function normalizeEmail(email: string): string {
  return email.trim().toLowerCase();
}

function normalizePhone(phone: string): string {
  return phone.replace(/\D/g, '');
}

/** User data that identifies the converter. PII gets hashed before
 *  transport; cookie identifiers + IP + user-agent are clear-text
 *  per Facebook spec. */
export type MetaCapiUserData = {
  /** Plain email — hashed here before transport. */
  email?: string | null;
  /** Plain phone (any format, digits will be extracted). */
  phone?: string | null;
  /** _fbp browser cookie value (e.g. 'fb.1.1700000000.123456789').
   *  Set by the Pixel on every page; read from document.cookie
   *  client-side and forwarded server-side. */
  fbp?: string | null;
  /** _fbc browser cookie value (e.g. 'fb.1.1700000000.<fbclid>').
   *  Set by the Pixel when an fbclid URL param is present; read
   *  client-side or reconstructed from raw fbclid (see
   *  buildFbcFromFbclid). */
  fbc?: string | null;
  /** Buyer IP — typically extract from x-forwarded-for. */
  ip?: string | null;
  /** Buyer user-agent — pass through from the request headers. */
  userAgent?: string | null;
};

export type MetaCapiEventParams = {
  /** Event name (e.g. 'Lead', 'CompleteRegistration', 'Purchase'). */
  event: string;
  /** Stable UUID generated by the CALLER. Must match the eventID
   *  used in the corresponding client-side fbq call for Facebook to
   *  dedupe. Pass crypto.randomUUID() if you don't have one. */
  eventId: string;
  /** Unix epoch SECONDS (not ms). Defaults to now. */
  eventTimeSeconds?: number;
  /** Full URL of the page where the conversion happened — improves
   *  attribution match rate. e.g. 'https://turfmap.ai/free-score'. */
  eventSourceUrl?: string | null;
  userData: MetaCapiUserData;
  /** Optional non-PII context (currency, value, content_name, etc.).
   *  Values must be primitives. */
  customData?: Record<string, string | number | boolean>;
  /** Defaults to 'website'. Use 'system_generated' for cron-fired
   *  events or 'app' for native-app events. */
  actionSource?: 'website' | 'app' | 'email' | 'system_generated' | 'other';
};

export type MetaCapiResult =
  | { ok: true; eventsReceived: number }
  | {
      ok: false;
      reason: 'not_configured' | 'http' | 'network' | 'parse';
      message: string;
    };

/** Reconstruct an _fbc cookie value from a raw fbclid. Used when
 *  the client didn't forward the cookie (e.g. cookie was cleared
 *  between page load + form submit) but DID forward the URL param.
 *
 *  Format per Facebook: fb.<subdomain_index>.<creation_time_ms>.<fbclid>
 *  Subdomain index 1 = top-level domain (most common). */
export function buildFbcFromFbclid(
  fbclid: string,
  creationTimeMs: number = Date.now()
): string {
  return `fb.1.${creationTimeMs}.${fbclid}`;
}

/** Send a single event to Meta's Conversions API.
 *
 *  Never throws — returns a Result. The caller decides whether to
 *  log the failure. Typical wiring: fire from inside an `after()`
 *  in a Next.js route so the response isn't blocked on a network
 *  hop to graph.facebook.com.
 */
export async function sendMetaCapiEvent(
  params: MetaCapiEventParams
): Promise<MetaCapiResult> {
  const pixelId = process.env.NEXT_PUBLIC_META_PIXEL_ID;
  const accessToken = process.env.META_CAPI_ACCESS_TOKEN;
  if (!pixelId || !accessToken) {
    return {
      ok: false,
      reason: 'not_configured',
      message:
        'Skipped: NEXT_PUBLIC_META_PIXEL_ID and/or META_CAPI_ACCESS_TOKEN are not set.',
    };
  }

  // Build user_data — hash PII, pass cookies/IP/UA in clear text.
  const u = params.userData;
  const userData: Record<string, string> = {};
  if (u.email) userData.em = sha256(normalizeEmail(u.email));
  if (u.phone) {
    const normalized = normalizePhone(u.phone);
    if (normalized) userData.ph = sha256(normalized);
  }
  if (u.fbp) userData.fbp = u.fbp;
  if (u.fbc) userData.fbc = u.fbc;
  if (u.ip) userData.client_ip_address = u.ip;
  if (u.userAgent) userData.client_user_agent = u.userAgent;

  const eventTime =
    params.eventTimeSeconds ?? Math.floor(Date.now() / 1000);

  type CapiEvent = {
    event_name: string;
    event_time: number;
    event_id: string;
    event_source_url?: string;
    action_source: NonNullable<MetaCapiEventParams['actionSource']>;
    user_data: Record<string, string>;
    custom_data?: Record<string, string | number | boolean>;
  };

  const eventPayload: CapiEvent = {
    event_name: params.event,
    event_time: eventTime,
    event_id: params.eventId,
    action_source: params.actionSource ?? 'website',
    user_data: userData,
  };
  if (params.eventSourceUrl) {
    eventPayload.event_source_url = params.eventSourceUrl;
  }
  if (params.customData && Object.keys(params.customData).length > 0) {
    eventPayload.custom_data = params.customData;
  }

  // Optional test-events code: when present, every event is tagged
  // with it so it shows up in Events Manager → Test Events. Use
  // this for end-to-end verification before flipping the live ad
  // campaign. UNSET this env var in production after you've
  // confirmed events are arriving.
  const testEventCode = process.env.META_CAPI_TEST_EVENT_CODE;

  const body: {
    data: CapiEvent[];
    test_event_code?: string;
  } = { data: [eventPayload] };
  if (testEventCode) body.test_event_code = testEventCode;

  const url = `https://graph.facebook.com/${FB_API_VERSION}/${encodeURIComponent(
    pixelId
  )}/events?access_token=${encodeURIComponent(accessToken)}`;

  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) {
      const text = await res.text().catch(() => '');
      return {
        ok: false,
        reason: 'http',
        message: `HTTP ${res.status}: ${text.slice(0, 500)}`,
      };
    }
    const data = (await res.json().catch(() => null)) as
      | { events_received?: number }
      | null;
    return {
      ok: true,
      eventsReceived: data?.events_received ?? 0,
    };
  } catch (e) {
    return {
      ok: false,
      reason: 'network',
      message: e instanceof Error ? e.message : String(e),
    };
  }
}
