/**
 * Idempotently create the Supabase Storage buckets TurfMap needs.
 *
 *   client-logos: public read (so the white-label portal can show the
 *   logo without auth), writes restricted to service-role (no RLS
 *   policies on insert == only service-role keys succeed). Files live
 *   under <client_id>/<filename>.
 *
 * Run with:  npm run init:storage
 */
import { config as loadEnv } from 'dotenv';
import path from 'node:path';
loadEnv({ path: path.resolve(process.cwd(), '.env.local') });
import { getServerSupabase } from '../lib/supabase/server';

const BUCKETS = [
  {
    id: 'client-logos',
    public: true,
    fileSizeLimit: 2 * 1024 * 1024, // 2 MB
    allowedMimeTypes: [
      'image/png',
      'image/jpeg',
      'image/webp',
      'image/svg+xml',
    ],
  },
  {
    // Roadmap PDFs + Strategist Prep Notes generated by the Phase 3
    // audit-milestones cron. PRIVATE — access is via signed URLs
    // emailed to the buyer (post-call) and Anthony (24h pre-call).
    // Files live under <audit_id>/{roadmap.pdf,prep-notes.md}.
    id: 'audit-roadmaps',
    public: false,
    fileSizeLimit: 10 * 1024 * 1024, // 10 MB — PDFs are typically <100kb
    // text/html added in Phase 3.1 — prep notes now render as
    // styled HTML at upload (see lib/audit/storage.ts) so operators
    // get a proper-looking deliverable when they open the signed
    // URL instead of unrendered markdown.
    allowedMimeTypes: ['application/pdf', 'text/html', 'text/markdown', 'text/plain'],
  },
];

async function main() {
  const supabase = getServerSupabase();
  for (const cfg of BUCKETS) {
    const { data: existing } = await supabase.storage.getBucket(cfg.id);
    if (existing) {
      // Existing bucket — sync the config in case anything has
      // drifted (e.g., we added text/html to allowedMimeTypes after
      // the bucket was first provisioned). updateBucket is a no-op
      // when nothing changed; cheap to always call.
      const { error } = await supabase.storage.updateBucket(cfg.id, {
        public: cfg.public,
        fileSizeLimit: cfg.fileSizeLimit,
        allowedMimeTypes: cfg.allowedMimeTypes,
      });
      if (error) {
        console.error(`✗ failed to update "${cfg.id}":`, error.message);
        process.exit(1);
      }
      console.log(`✓ bucket "${cfg.id}" config synced (public=${cfg.public})`);
      continue;
    }
    const { error } = await supabase.storage.createBucket(cfg.id, {
      public: cfg.public,
      fileSizeLimit: cfg.fileSizeLimit,
      allowedMimeTypes: cfg.allowedMimeTypes,
    });
    if (error) {
      console.error(`✗ failed to create "${cfg.id}":`, error.message);
      process.exit(1);
    }
    console.log(`+ created bucket "${cfg.id}"`);
  }
}
main().catch((e) => { console.error(e); process.exit(1); });
