-- 0013_alerts_exports.sql
--
-- Pulse / Pulse+ feature parity migration: alert preferences, Slack
-- webhook target, and Looker Studio export token. All three live on
-- the clients row because they're per-client config (not per-location,
-- not per-keyword).
--
-- Alert preferences are stored as a single JSONB blob (`alert_prefs`)
-- rather than a column-per-toggle because the surface is going to keep
-- growing — every new alert type would otherwise mean another
-- migration. Defaults match the marketing-page promises:
--   - score-movement email: ON, threshold 5 points
--   - competitor-entries email: ON
--   - momentum-reversal email: ON
--   - cell-level-changes email: OFF (noisy by default; opt-in)
--   - weekly competitor summary: ON
-- Operators flip toggles via the new SettingsForm card in 0013's UI work.
--
-- Slack: store the incoming-webhook URL the operator pasted from
-- Slack's Apps → Incoming Webhooks setup. POST to it to deliver
-- alerts; nothing else needed (no OAuth dance).
--
-- Looker Studio: generate a random per-client token; the export
-- endpoint authenticates on token alone (no agency cookie needed,
-- since Looker is pulling the data without a logged-in session).
-- Operator generates / revokes via the new Exports card.

alter table clients
  add column if not exists alert_prefs jsonb not null default
    jsonb_build_object(
      'score_movement_email', true,
      'score_movement_threshold', 5,
      'competitor_entries_email', true,
      'momentum_reversal_email', true,
      'cell_changes_email', false,
      'weekly_competitor_summary_email', true
    );

alter table clients
  add column if not exists slack_webhook_url text;

-- Looker token. Random 32-char string generated by the route handler
-- when the operator clicks "Generate token" on the Exports card.
-- Nullable: clients without a token can't be queried by Looker.
alter table clients
  add column if not exists looker_token text unique;

-- Per-alert-type debounce: when did we last fire this alert type for
-- this client? Prevents 6-am rescue alerts when a single bad scan
-- keeps the scores below threshold across multiple polls. Stored as
-- a JSONB map keyed by alert type → last-fired-iso.
alter table clients
  add column if not exists alerts_last_fired_at jsonb not null default '{}'::jsonb;

create index if not exists idx_clients_looker_token
  on clients(looker_token)
  where looker_token is not null;
