-- 0022_visibility_audits.sql
--
-- Visibility Audit fulfillment pipeline (Phase 1 — foundation only).
--
-- Two new tables:
--
--   visibility_audits  — one row per Visibility Audit purchase. Tracks
--                        the full lifecycle: call scheduling, completion,
--                        Roadmap PDF, prep notes, 60-day check-in,
--                        Lift Promise verification, LLM Fit Score, and
--                        post-call snippet selection.
--
--   roadmap_actions    — line items inside each audit's 12-week
--                        Roadmap. Generated by the AI Roadmap Generator
--                        and used to power the dashboard execution
--                        checklist + Lift Promise verification.
--
-- Phase 1 wires the schema + populates rows via the fulfill route on
-- audit purchase. Roadmap PDF rendering, Cal.com booking widget, cron
-- sweeps for reminders, and dashboard UI come in subsequent phases —
-- the columns for those (roadmap_pdf_url, sixty_day_*, etc.) start
-- NULL and get populated as later phases land.
--
-- Apply via the Supabase SQL editor. Safe to re-run.

-- ─── Table: visibility_audits ──────────────────────────────────────────

create table if not exists visibility_audits (
  id uuid primary key default gen_random_uuid(),

  -- Foreign keys to existing rows. lead_order_id is the source of
  -- truth for "which Stripe purchase fulfilled this audit." scan_id
  -- references the buyer's primary scan that the Roadmap is built
  -- against. client_id is denormalized for query convenience (we
  -- could derive it from lead_orders, but joining on every dashboard
  -- read is wasteful).
  lead_order_id uuid not null references lead_orders(id) on delete cascade,
  scan_id uuid not null references scans(id) on delete restrict,
  client_id uuid not null references clients(id) on delete cascade,

  -- Lifecycle state. Transitions:
  --   pending_call_schedule  → buyer just paid, hasn't picked a Cal.com slot
  --   call_scheduled         → Cal.com BOOKING_CREATED webhook fired
  --   call_completed         → operator marked complete OR Cal.com
  --                            BOOKING_ENDED fired (whichever comes first)
  --   post_call_sent         → Anthony sent the post-call Superhuman snippet
  --   sixty_day_prompted     → day-53 prompt email landed in buyer's inbox
  --   sixty_day_completed    → 60-day check-in call wrapped
  status text not null default 'pending_call_schedule'
    check (status in (
      'pending_call_schedule',
      'call_scheduled',
      'call_completed',
      'post_call_sent',
      'sixty_day_prompted',
      'sixty_day_completed'
    )),

  -- Strategist call lifecycle timestamps.
  strategist_call_scheduled_at timestamptz,
  strategist_call_completed_at timestamptz,
  post_call_email_sent_at timestamptz,

  -- 60-day check-in lifecycle.
  sixty_day_prompted_at timestamptz,
  sixty_day_check_scheduled_at timestamptz,
  sixty_day_check_completed_at timestamptz,

  -- Generated artifacts. Set as Phase 2 (PDF) + Phase 3 (Superhuman)
  -- pipelines populate them. Both are signed Supabase Storage URLs
  -- with 90-day expiries; we re-mint when they expire.
  roadmap_pdf_url text,
  prep_notes_url text,

  -- TurfScore Lift Promise tracking.
  starting_turfscore integer,                  -- score at audit purchase
  lift_promise_target_score integer,           -- AI-projected 30-day target
  actual_lift_score integer,                   -- post-rescan score (day 30)
  lift_promise_met boolean,                    -- null until 30-day re-scan lands

  -- LLM Fit Score (1-5, deterministic from rules in lib/audit/llmFitScore.ts).
  -- Stored as a column rather than recomputed on read because the
  -- inputs (Apollo enrichment, review counts) can drift after the
  -- audit is purchased — we want the score that informed the
  -- strategist call, not the score the data shows today.
  llm_fit_score integer check (llm_fit_score between 1 and 5),
  -- JSON breakdown of how the score was computed (input signals +
  -- rule hits). Exposed in the prep notes so Anthony can see why
  -- the score landed where it did.
  llm_fit_breakdown jsonb,

  -- Snippet selection at post-call time. 'llm_pitch' for Fit 4-5,
  -- 'audit_only' for Fit 1-3. Set when Phase 3 fires the Superhuman
  -- staging.
  snippet_used text check (snippet_used in ('llm_pitch', 'audit_only')),

  -- LLM application funnel state.
  llm_application_sent_at timestamptz,
  llm_application_completed_at timestamptz,

  -- Phase 4 / Fathom integration landing zone. Populated by the
  -- Fathom webhook when a recording matches a scheduled audit call.
  fathom_recording_url text,
  fathom_summary text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- One audit per lead_order. If the buyer somehow re-purchases (edge
  -- case post-refund), they'd get a new lead_orders row + a new audit.
  unique (lead_order_id)
);

create index if not exists visibility_audits_client_id_idx
  on visibility_audits (client_id);

create index if not exists visibility_audits_status_idx
  on visibility_audits (status);

-- Phase 3 milestone-sweep crons hit this index hardest. Day-25
-- reminder + day-53 60-day prompt + day-67 follow-up all filter on
-- strategist_call_completed_at + status, so a partial index keyed
-- on completed-but-not-finalized rows keeps the sweep fast as the
-- table grows.
create index if not exists visibility_audits_milestone_idx
  on visibility_audits (strategist_call_completed_at)
  where strategist_call_completed_at is not null
    and status not in ('sixty_day_completed');

comment on table visibility_audits is
  'One row per Visibility Audit purchase. Tracks call lifecycle, Roadmap PDF, prep notes, 60-day check-in, Lift Promise verification, and LLM Fit Score. Populated on audit fulfillment; PDF/snippet/cron-sweep wiring lands in subsequent phases.';

comment on column visibility_audits.llm_fit_breakdown is
  'JSON breakdown of how llm_fit_score was computed. Includes the input signals (revenue band, trade fit, metro fit, ad activity, review count) and which rules fired. Surfaced in prep notes.';

-- ─── Table: roadmap_actions ────────────────────────────────────────────

create table if not exists roadmap_actions (
  id uuid primary key default gen_random_uuid(),
  audit_id uuid not null references visibility_audits(id) on delete cascade,

  -- Week 1-12 across the three phases:
  --   Weeks 1-4   = Foundation
  --   Weeks 5-8   = Authority
  --   Weeks 9-12  = Optimization
  week_number integer not null check (week_number between 1 and 12),

  -- Display-ready copy from the AI Roadmap Generator.
  action_text text not null,

  -- Action category — drives the dashboard nudge text + LLM service
  -- mapping. Constrained to the categories defined in
  -- lib/audit/actionCategories.ts so a future schema typo can't
  -- silently desync the nudge config. 'other' is the catchall for
  -- buyer-specific actions that don't fit the named categories
  -- (e.g., trade-specific opportunities the AI surfaces).
  action_category text not null check (action_category in (
    'review_velocity',
    'directory_claiming',
    'gbp_optimization',
    'gbp_photos',
    'schema_integration',
    'nap_consistency',
    'other'
  )),

  -- AI-projected score lift if this action lands (independent of
  -- other actions — the cumulative projection is computed in code,
  -- not stored, so we can apply diminishing-returns shaping if we
  -- decide the AI's per-action numbers are too generous to sum
  -- linearly).
  projected_score_lift integer not null check (projected_score_lift >= 0),

  difficulty_rating text not null check (difficulty_rating in (
    'DIY-easy',
    'DIY-medium',
    'DIY-hard'
  )),

  priority text not null check (priority in ('HIGH', 'MEDIUM', 'LOW')),

  -- TRUE for actions covered by Local Lead Machine. Drives the 📍
  -- LLM tag in the PDF and the dashboard nudges. Determined by the
  -- action_category mapping in lib/audit/actionCategories.ts at
  -- generation time, not recomputed on read.
  llm_covered boolean not null default false,

  -- Buyer execution tracking — populates from dashboard checkbox
  -- clicks. completed_at is the verification timestamp at 30-day
  -- re-scan time for Lift Promise validation.
  completed boolean not null default false,
  completed_at timestamptz,

  created_at timestamptz not null default now()
);

create index if not exists roadmap_actions_audit_id_idx
  on roadmap_actions (audit_id, week_number);

create index if not exists roadmap_actions_completed_idx
  on roadmap_actions (audit_id, completed);

comment on table roadmap_actions is
  'Line items in each Visibility Audit Roadmap. Generated once at audit fulfillment; buyer marks complete from the dashboard. Drives PDF page 4 and Lift Promise verification at 30-day re-scan.';

-- ─── RLS ──────────────────────────────────────────────────────────────
--
-- Visibility audits + their actions follow the same access pattern
-- as scans:
--   - Service role (server-side fulfill route, cron sweeps): full access
--   - Authenticated agency staff: read on audits for clients they
--     can access (existing clients RLS handles the visibility cascade)
--   - Portal users (buyers viewing their own audit): read on their
--     own audit + actions only; update on actions.completed only

alter table visibility_audits enable row level security;
alter table roadmap_actions enable row level security;

-- Agency staff: read access to all audits (mirrors clients RLS).
-- The existing clients-table policies already gate which clients an
-- agency user can see; mirroring that here would duplicate the
-- predicate. Simpler to grant blanket read for authenticated users
-- because the only way to GET an audit row is via a client_id the
-- agency user already knows about.
create policy "agency staff read audits"
  on visibility_audits
  for select
  to authenticated
  using (true);

create policy "agency staff read actions"
  on roadmap_actions
  for select
  to authenticated
  using (true);

-- Portal users: read + update-completed on their own audit.
-- The portal-user → client membership is already enforced upstream
-- (portal_users table + getPortalUser helper) — by the time a portal
-- user has an authenticated session, the client_id they have access
-- to is decided. Per-audit access flows from that.
--
-- We don't add an INSERT policy: audits are only inserted by the
-- service-role fulfill route. Same for DELETE — audits are
-- soft-archived via status, never hard-deleted, except via the
-- cascade from clients.

-- Service role bypasses RLS entirely (Supabase default), so no
-- explicit policy needed for the fulfill route + cron sweeps.

-- ─── updated_at trigger ────────────────────────────────────────────────

create or replace function visibility_audits_set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists visibility_audits_updated_at on visibility_audits;
create trigger visibility_audits_updated_at
  before update on visibility_audits
  for each row
  execute function visibility_audits_set_updated_at();
