-- 0024_prospects.sql
--
-- Cold-email outreach pipeline. The lead-gen system (Mac launchd
-- script, runs weekly) generates a batch of prospect records, sends
-- the outreach email, and includes a personalized URL pointing at
-- /yourmap?prospect_id=<id>. The page reads this row server-side
-- to render personalized hero copy.
--
-- Prospect data is captured at lead-gen time (preview scan run +
-- competitor analysis) and stored here. The page renders it; the
-- Stripe-checkout flow stamps converted_at when a buyer from this
-- channel actually purchases TurfScan; the audit-upgrade flow
-- stamps upgraded_to_audit_at if they later upgrade.
--
-- ID is a 10-char nanoid (text PK, NOT a uuid) generated by the
-- lead-gen pipeline. Short enough to fit in cold-email subject
-- lines + URLs without breaking line wrap.
--
-- Apply via the Supabase SQL editor. Safe to re-run.

create table if not exists prospects (
  id text primary key,
  business_name text not null,
  city text not null,
  trade text not null,
  preview_score integer not null check (preview_score between 0 and 100),
  invisibility_count integer not null check (invisibility_count between 0 and 81),
  top_competitor_name text,
  top_competitor_share_pct integer
    check (top_competitor_share_pct is null or top_competitor_share_pct between 0 and 100),
  email_sent_at timestamptz,
  email_campaign text,
  source_pipeline_run_id text,
  page_viewed_at timestamptz,
  view_count integer not null default 0,
  converted_at timestamptz,
  upgraded_to_audit_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists prospects_email_campaign_idx
  on prospects (email_campaign);

create index if not exists prospects_created_at_idx
  on prospects (created_at);

-- Conversion-funnel queries hit these often: "how many prospects
-- viewed but didn't convert in campaign X" / "what's the upgrade
-- rate of converted cold-email cohort." Partial indexes keep them
-- cheap as the table grows.
create index if not exists prospects_converted_idx
  on prospects (converted_at)
  where converted_at is not null;

create index if not exists prospects_upgraded_idx
  on prospects (upgraded_to_audit_at)
  where upgraded_to_audit_at is not null;

comment on table prospects is
  'Cold-email outreach prospects. Written by the lead-gen pipeline (Mac launchd, weekly). Read by /yourmap landing page for personalization. Converted_at stamped on TurfScan purchase; upgraded_to_audit_at on audit-tier upgrade.';

comment on column prospects.id is
  '10-char nanoid generated by the lead-gen pipeline. Embedded in cold-email URLs as ?prospect_id=<id>.';

comment on column prospects.preview_score is
  'TurfScore (0-100) computed by the lead-gen pipeline''s preview scan. Used for hero-block personalization on /yourmap.';

comment on column prospects.invisibility_count is
  'Count of cells where the prospect is outside the visible 3-pack (rank > 3 OR absent). 0-81. Driven by the preview scan.';

-- ─── RLS ──────────────────────────────────────────────────────────────
--
-- Service-role only. The /api/prospect/[id] route uses the service-
-- role client to look up + stamp views. Public anon reads would let
-- anyone enumerate the table; we instead expose a single rate-limited
-- endpoint that returns one row at a time.

alter table prospects enable row level security;

-- No public/authenticated policies — the table is service-role-only.
-- Service-role bypasses RLS by default in Supabase, so no policy is
-- needed for the legitimate read/write paths.
